In [1]:
# imports
import numpy as np
import pandas as pd

# Challange-1

Consider the Weather dataset and perform KNN Classification by choosing optimal k-value

In [2]:
data= pd.read_csv("Weather-dataset.csv")
data

     Outlook  Temp Humidity  Windy Play
0      Rainy   Hot     High  False   No
1      Rainy   Hot     High   True   No
2   Overcast   Hot     High  False  Yes
3      Sunny  Mild     High  False  Yes
4      Sunny  Cool   Normal  False  Yes
5      Sunny  Cool   Normal   True   No
6   Overcast  Cool   Normal   True  Yes
7      Rainy  Mild     High  False   No
8      Rainy  Cool   Normal  False  Yes
9      Sunny  Mild   Normal  False  Yes
10     Rainy  Mild   Normal   True  Yes
11  Overcast  Mild     High   True  Yes
12  Overcast   Hot   Normal  False  Yes
13     Sunny  Mild     High   True   No

In [3]:
# Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
# Converting string labels into numbers.
data['Outlook']=le.fit_transform(data['Outlook'])
data['Temp']=le.fit_transform(data['Temp'])
data['Humidity']=le.fit_transform(data['Humidity'])
data['Windy']=le.fit_transform(data['Windy'])
data['Play']=le.fit_transform(data['Play'])

In [4]:
data

    Outlook  Temp  Humidity  Windy  Play
0         1     1         0      0     0
1         1     1         0      1     0
2         0     1         0      0     1
3         2     2         0      0     1
4         2     0         1      0     1
5         2     0         1      1     0
6         0     0         1      1     1
7         1     2         0      0     0
8         1     0         1      0     1
9         2     2         1      0     1
10        1     2         1      1     1
11        0     2         0      1     1
12        0     1         1      0     1
13        2     2         0      1     0

In [6]:
from sklearn.model_selection import train_test_split
x = data.drop(['Play'], axis=1).values 
y = data['Play']
X_train, X_test, y_train, y_test =  train_test_split(x,y,test_size = 0.2, random_state= 2)

In [8]:
from sklearn.neighbors import KNeighborsClassifier

#Create KNN Classifier
knn = KNeighborsClassifier(n_neighbors=3)

#Train the model using the training sets
knn.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = knn.predict(X_test)

In [9]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.6666666666666666

In [10]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 1.0

# Challange-2

Apply Cross-validation on the given Weather dataset and print the accuracy.

In [11]:
data

    Outlook  Temp  Humidity  Windy  Play
0         1     1         0      0     0
1         1     1         0      1     0
2         0     1         0      0     1
3         2     2         0      0     1
4         2     0         1      0     1
5         2     0         1      1     0
6         0     0         1      1     1
7         1     2         0      0     0
8         1     0         1      0     1
9         2     2         1      0     1
10        1     2         1      1     1
11        0     2         0      1     1
12        0     1         1      0     1
13        2     2         0      1     0

In [12]:
from sklearn.model_selection import train_test_split
X = data.drop(['Play'], axis=1).values 
y = data['Play']
X_train, X_validation, Y_train, Y_validation = train_test_split(X, y, test_size=0.2, random_state=2)

In [13]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()

In [15]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
kfold = StratifiedKFold(n_splits=3, random_state=2, shuffle=True)
cv_results = cross_val_score(knn, X_train, Y_train, cv=kfold, scoring='accuracy')
print('%f (%f)' % (cv_results.mean(), cv_results.std()))

0.666667 (0.235702)

In [16]:
knn.fit(X_train, Y_train)
predictions = knn.predict(X_validation)

In [17]:
from sklearn.metrics import accuracy_score
print("Accuracy:",accuracy_score(Y_validation, predictions))

Accuracy: 1.0